In [18]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
rute= '/home/ubuntu/Database/ALL/Videos'
folder= 'Littering'  # Replace with your folder name
video = '3_074_1.mp4'  # Replace with your video name
cap = cv2.VideoCapture(f"{rute}/{folder}/{video}")
frames = np.load("..//Database/ALL/GT/gt_ALL.npz")
frames = frames[video.split('.')[0]]
frames = np.append(frames, frames[-1])
stored=[]
print(frames)
while cap.isOpened():   
    ret, frame = cap.read()
    if not ret:
        break
    # Display the frame
    print(cap.get(cv2.CAP_PROP_POS_FRAMES))
    if frames[int(cap.get(cv2.CAP_PROP_POS_FRAMES)) - 1] == 1 and int(cap.get(cv2.CAP_PROP_POS_FRAMES))%5 == 0:
        cv2.imwrite(f"/home/ubuntu/Tesis/ASK/Littering/{video.split('.')[0]}_frame_{int(cap.get(cv2.CAP_PROP_POS_FRAMES))}.jpg", frame)
        stored.append(frame)
    cv2.imshow('Frame', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [19]:
file='4_076_1_CLIP_0_a video of a person riding a bicycle on the street.npy'
rute= '/home/ubuntu/Tesis/Storage/Score_Rules_NewScores'
frames_number=stored[0]
descriptions=stored[1]
probabilities=stored[3]
stored=np.load(f"{rute}/{file}",allow_pickle=True)
print(stored.shape)

(4,)


In [ ]:
import numpy as np

# Example: 3 classes, 6 frames
prob_vec = np.array(
    [0.1, 0.3, 0.5, 0.7, 0.2, 0.4],  # Class 0 probabilities
)
prob_matrix = prob_vec.T
# Create a matrix with 6 rows (each row is a class), columns are probability vectors
prob_matrix = np.column_stack([
    np.array([0.1, 0.3, 0.5, 0.7, 0.2, 0.4]),  # Class 0
    np.array([0.2, 0.4, 0.6, 0.8, 0.3, 0.5]),  # Class 1
    np.array([0.3, 0.5, 0.7, 0.9, 0.4, 0.6]),  # Class 2
    np.array([0.4, 0.6, 0.8, 1.0, 0.5, 0.7]),  # Class 3
    np.array([0.5, 0.7, 0.9, 1.1, 0.6, 0.8]),  # Class 4
    prob_vec   # Class 5
])
prob_matrix = np.column_stack([
    prob_matrix,  # Class 0
    np.array([0.2, 0.4, 0.6, 0.8, 0.3, 0.5]),  # Class 1
    np.array([0.3, 0.5, 0.7, 0.9, 0.4, 0.6]),  # Class 2
    np.array([0.4, 0.6, 0.8, 1.0, 0.5, 0.7]),  # Class 3
    np.array([0.5, 0.7, 0.9, 1.1, 0.6, 0.8]),  # Class 4
    prob_vec   # Class 5
])
if prob_matrix.shape[1]>6:
    prob_matrix = prob_matrix[:, :6]  # Ensure we only keep the first 6 columns
print("Original probabilities:\n", prob_matrix.shape)

window_size = 3
kernel = np.ones(window_size) / window_size  # Uniform smoothing

# Apply convolution to each class (row)
smoothed_matrix = np.vstack([
    np.convolve(row, kernel, mode='same')
    for row in prob_matrix
])

print("Original:\n", prob_matrix)
print("Smoothed:\n", smoothed_matrix.round(2))

# Calculate the mean of each row in the smoothed matrix
row_means = smoothed_matrix.mean(axis=1)
print("Row means:\n", row_means)
index= np.argmax(row_means)
print("Index of class with highest mean probability:", index)

Original probabilities:
 (6, 11)
Original:
 [[0.1 0.2 0.3 0.4 0.5 0.1 0.2 0.3 0.4 0.5 0.1]
 [0.3 0.4 0.5 0.6 0.7 0.3 0.4 0.5 0.6 0.7 0.3]
 [0.5 0.6 0.7 0.8 0.9 0.5 0.6 0.7 0.8 0.9 0.5]
 [0.7 0.8 0.9 1.  1.1 0.7 0.8 0.9 1.  1.1 0.7]
 [0.2 0.3 0.4 0.5 0.6 0.2 0.3 0.4 0.5 0.6 0.2]
 [0.4 0.5 0.6 0.7 0.8 0.4 0.5 0.6 0.7 0.8 0.4]]
Smoothed:
 [[0.1  0.2  0.3  0.4  0.33 0.27 0.2  0.3  0.4  0.33 0.2 ]
 [0.23 0.4  0.5  0.6  0.53 0.47 0.4  0.5  0.6  0.53 0.33]
 [0.37 0.6  0.7  0.8  0.73 0.67 0.6  0.7  0.8  0.73 0.47]
 [0.5  0.8  0.9  1.   0.93 0.87 0.8  0.9  1.   0.93 0.6 ]
 [0.17 0.3  0.4  0.5  0.43 0.37 0.3  0.4  0.5  0.43 0.27]
 [0.3  0.5  0.6  0.7  0.63 0.57 0.5  0.6  0.7  0.63 0.4 ]]
Row means:
 [0.27575758 0.46363636 0.65151515 0.83939394 0.36969697 0.55757576]
Index of class with highest mean probability: 3


In [16]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# Example: 4 samples, 3 features, 3 classes
X = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [10.0, 11.0, 12.0]])
y = np.array([0, 1, 2, 4])  # 3 classes (0, 1, 2)
print(X)
print(X.shape, y.shape)
clf = LogisticRegression(multi_class='multinomial', solver='lbfgs')
clf.fit(X, y)  # Same data as above
print("Coefficients (Weights):\n", clf.coef_)
print("Intercepts (Bias):\n", clf.intercept_)
print(clf.coef_* X[1] + clf.intercept_[1], "==", clf.predict_proba([X[1]])[0])

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
(4, 3) (4,)
Coefficients (Weights):
 [[-0.48183734 -0.48190132 -0.48196529]
 [-0.13559313 -0.13554216 -0.1354912 ]
 [ 0.13552262  0.13553664  0.13555066]
 [ 0.48190785  0.48190684  0.48190583]]
Intercepts (Bias):
 [  7.90632307   4.13375846  -1.15203763 -10.8880439 ]
[[2.20640908 1.72425187 1.2419667 ]
 [3.59138595 3.45604764 3.32081126]
 [4.67584893 4.81144166 4.94706244]
 [6.06138987 6.54329266 7.02519344]] == [0.15653464 0.64958257 0.19183623 0.00204656]
